# 运行模式
RunMode = "debug"

# 是否启用swagger
Swagger = true

[HTTP]
# http监听地址
Host = "0.0.0.0"
# http监听端口
Port = 11888
# 证书路径
CertFile = ""
# 证书密钥
KeyFile = ""
# http优雅关闭等待超时时长(单位秒)
ShutdownTimeout = 30
# 允许的最大内容长度(64M)
MaxContentLength = 67108864
# 允许输出的最大日志长度
MaxLoggerLength = 4096

[CORS]
# 是否启用
Enable = false
# 允许跨域请求的域名列表(*表示全部允许)
AllowOrigins = ["*"]
# 允许跨域请求的请求方式列表
AllowMethods = ["GET", "POST", "PUT", "DELETE", "PATCH"]
# 允许客户端与跨域请求一起使用的非简单标头的列表
AllowHeaders = []
# 请求是否可以包含cookie，HTTP身份验证或客户端SSL证书等用户凭据
AllowCredentials = true
# 可以缓存预检请求结果的时间（以秒为单位）
MaxAge = 7200

[GZIP]
# 是否启用
Enable = false
# 排除的文件扩展名
ExcludedExtentions = [".png", ".gif", ".jpeg", ".jpg"]
# 排除的请求路径
ExcludedPaths = []

[MINIO]
Debug = false
AutoMakeBucket = true
# 连接地址
Endpoint = "localhost:9000"
AccessKeyID = "toQVQar56ALcXP4k0oNv"
SecretAccessKey = "7styo8rKK73AqZZlJ9qC4rtIJH74NOtnmG9YD9oN"
UseSSL = false

[Redis]
# 地址
Addr = "127.0.0.1:6379"
# 密码
Password = ""

[JWTAuth]
# 是否启用
Enable = true
# 签名方式(支持：HS512/HS384/HS512)
SigningMethod = "HS512"
# 签名key
SigningKey = "gin-admin"
# 过期时间（单位秒）
Expired = 7200
# 存储(支持：file/redis)
Store = "redis"
# 文件路径
FilePath = "data/jwt_auth.db"
# redis数据库(如果存储方式是redis，则指定存储的数据库)
RedisDB = 10
# 存储到redis数据库中的键名前缀
RedisPrefix = "auth_"

[Log]
# 日志级别(1:fatal 2:error,3:warn,4:info,5:debug,6:trace)
Level = 5
# 日志格式（支持输出格式：text/json）
Format = "text"
# 日志输出(支持：stdout/stderr/file)
Output = "stdout"
# 指定日志输出的文件路径
OutputFile = "data/file-server.log"

# 请求频率限制(如果redis可用则使用redis，否则使用内存存储)
[RateLimiter]
# 是否启用
Enable = false
# 每分钟每个用户允许的最大请求数量
Count = 300
# redis数据库(如果存储方式是redis，则指定存储的数据库)
RedisDB = 10
