// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"fileServer/app/api"
	"fileServer/app/model/minio/bucket"
	"fileServer/app/router"
	"fileServer/app/service"
)

// Injectors from wire.go:

// BuildInjector 生成注入器
func BuildInjector() (*Injector, func(), error) {
	auther, cleanup, err := InitAuth()
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := InitMinio()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	fileBucket := &bucket.FileBucket{
		MinioClient: client,
	}
	avatar := &service.Avatar{
		FileModel: fileBucket,
	}
	apiAvatar := &api.Avatar{
		AvatarSrv: avatar,
	}
	fileServer := &service.FileServer{
		FileModel: fileBucket,
	}
	fileApi := &api.FileApi{
		FileSrv: fileServer,
	}
	routerRouter := &router.Router{
		Auth:      auther,
		AvatarAPI: apiAvatar,
		FileAPI:   fileApi,
	}
	engine := InitGinEngine(routerRouter)
	injector := &Injector{
		Engine: engine,
		Auth:   auther,
	}
	return injector, func() {
		cleanup2()
		cleanup()
	}, nil
}
