definitions:
  schema.ErrorItem:
    properties:
      code:
        description: 错误码
        type: integer
      message:
        description: 错误信息
        type: string
    type: object
  schema.ErrorResult:
    properties:
      error:
        allOf:
        - $ref: '#/definitions/schema.ErrorItem'
        description: 错误项
    type: object
  schema.IDResult:
    properties:
      id:
        type: string
    type: object
  schema.StatusResult:
    properties:
      status:
        allOf:
        - $ref: '#/definitions/schema.StatusText'
        description: 状态(OK)
    type: object
  schema.StatusText:
    enum:
    - OK
    - ERROR
    - FAIL
    type: string
    x-enum-varnames:
    - OKStatus
    - ErrorStatus
    - FailStatus
info:
  contact: {}
paths:
  /file-api/v1/avatars:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.IDResult'
        "400":
          description: '{error:{code:0,message:无效的请求参数}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 上传头像
      tags:
      - Avatar
  /file-api/v1/files/{fileName}:
    delete:
      parameters:
      - description: 唯一标识
        in: path
        name: fileName
        required: true
        type: string
      responses:
        "200":
          description: '{status:OK}'
          schema:
            $ref: '#/definitions/schema.StatusResult'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 删除文件
      tags:
      - File
    get:
      parameters:
      - description: 唯一标识
        in: path
        name: fileName
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: '{error:{code:0,message:无效的请求参数}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 下载指定文件
      tags:
      - File
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 唯一标识
        in: path
        name: fileName
        required: true
        type: string
      - description: file
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.IDResult'
        "400":
          description: '{error:{code:0,message:无效的请求参数}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 上传文件
      tags:
      - File
swagger: "2.0"
